/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of BarcodeResponse
 */
interface BarcodeResponse {
  fault?: Fault;
}

export class BarcodeResponseError extends ApiError<BarcodeResponse> {}
