/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error5 } from '../models/error5';

/**
 * Creates an instance of BarcodeResponseInvalid
 */
interface BarcodeResponseInvalid {
  /** A list of errors. See [Error codes](#tag/Error-codes) for possible values. */
  errors?: Error5[];
}

export class BarcodeResponseInvalidError extends ApiError<BarcodeResponseInvalid> {}
