/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ResponseShipment } from '../models/responseShipment';

/**
 * Creates an instance of ConfirmingResponse
 */
interface ConfirmingResponse {
  ResponseShipments?: ResponseShipment[];
}

export class ConfirmingResponseError extends ApiError<ConfirmingResponse> {}
