/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of ConfirmingResponseError1
 */
interface ConfirmingResponseError1 {
  fault?: Fault;
}

export class ConfirmingResponseError1Error extends ApiError<ConfirmingResponseError1> {}
