/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error } from '../models/error';

/**
 * Creates an instance of CpcResponseInvalid
 */
interface CpcResponseInvalid {
  errors?: Error[];
}

export class CpcResponseInvalidError extends ApiError<CpcResponseInvalid> {}
