/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error1 } from '../models/error1';

/**
 * Creates an instance of LocationsResponseInvalid
 */
interface LocationsResponseInvalid {
  Date?: string;
  Error?: Error1;
  RequestId?: string;
}

export class LocationsResponseInvalidError extends ApiError<LocationsResponseInvalid> {}
