/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PostCIFTimeframeTooManyRequest
 */
interface PostCIFTimeframeTooManyRequest {
  message?: string;
  http_status_code?: number;
}

export class PostCIFTimeframeTooManyRequestError extends ApiError<PostCIFTimeframeTooManyRequest> {}
