/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PostCIFTimeframeMethodNotAllowed
 */
interface PostCIFTimeframeMethodNotAllowed {
  message?: string;
  http_status_code?: number;
}

export class PostCIFTimeframeMethodNotAllowedError extends ApiError<PostCIFTimeframeMethodNotAllowed> {}
