/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of ShippingstatusResponse
 */
interface ShippingstatusResponse {
  fault?: Fault;
}

export class ShippingstatusResponseError extends ApiError<ShippingstatusResponse> {}
