/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** The pickup location address */
export interface Address1 {
  /** The pickup location street */
  street?: string;
  /** The pickup location zipcode */
  zipcode?: string;
  /** The pickup location housenumber */
  houseNr?: number;
  /** The pickup location housenumber extension */
  houseNrExt?: string;
  /** The pickup location country */
  countrycode?: string;
  /** The pickup location company name */
  companyName?: string;
}

export const address1Schema: Schema<Address1> = object({
  street: ['Street', optional(string())],
  zipcode: ['Zipcode', optional(string())],
  houseNr: ['HouseNr', optional(number())],
  houseNrExt: ['HouseNrExt', optional(string())],
  countrycode: ['Countrycode', optional(string())],
  companyName: ['CompanyName', optional(string())],
});
