/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Address2 {
  /** The city of the pickup location address */
  city?: string;
  /** The country of the pickup location address */
  countrycode?: string;
  /** The house number of the pickup location address */
  houseNr?: number;
  /** The house number extension of the pickup location address */
  houseNrExt?: string;
  /** Additional information about the pickup location */
  remark?: string;
  /** The street of the pickup location address */
  street?: string;
  /** The zipcode of the pickup location address */
  zipcode?: string;
}

export const address2Schema: Schema<Address2> = object({
  city: ['City', optional(string())],
  countrycode: ['Countrycode', optional(string())],
  houseNr: ['HouseNr', optional(number())],
  houseNrExt: ['HouseNrExt', optional(string())],
  remark: ['Remark', optional(string())],
  street: ['Street', optional(string())],
  zipcode: ['Zipcode', optional(string())],
});
