/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The amounts belonging to the shipment */
export interface Amount1 {
  /** The cash-on-delivery (COD) amount */
  remboursBedrag?: string;
  /** The insurance amount of the shipment */
  verzekerdBedrag?: string;
}

export const amount1Schema: Schema<Amount1> = object({
  remboursBedrag: ['RemboursBedrag', optional(string())],
  verzekerdBedrag: ['VerzekerdBedrag', optional(string())],
});
