/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CodeEnum
 */
export enum CodeEnum {
  Enum00 = '00',
  Enum01 = '01',
  Enum02 = '02',
  Enum03 = '03',
}

/**
 * Schema for CodeEnum
 */
export const codeEnumSchema: Schema<CodeEnum> = stringEnum(CodeEnum);
