/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Shipment1, shipment1Schema } from './shipment1';

/** The current status and old statuses of the shipment */
export interface CompleteStatus {
  shipment?: Shipment1[];
}

export const completeStatusSchema: Schema<CompleteStatus> = object({
  shipment: ['Shipment', optional(array(lazy(() => shipment1Schema)))],
});
