/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ResponseShipment, responseShipmentSchema } from './responseShipment';

export interface ConfirmingResponse {
  responseShipments?: ResponseShipment[];
}

export const confirmingResponseSchema: Schema<ConfirmingResponse> = object({
  responseShipments: [
    'ResponseShipments',
    optional(array(lazy(() => responseShipmentSchema))),
  ],
});
