/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Customer, customerSchema } from './customer';
import { Message, messageSchema } from './message';
import { Shipment, shipmentSchema } from './shipment';

export interface ConfirmingRequest {
  customer: Customer;
  message: Message;
  /** List of 1 or more Shipments. At least 1 shipment is required. */
  shipments: Shipment[];
}

export const confirmingRequestSchema: Schema<ConfirmingRequest> = object({
  customer: ['Customer', lazy(() => customerSchema)],
  message: ['Message', lazy(() => messageSchema)],
  shipments: ['Shipments', array(lazy(() => shipmentSchema))],
});
