/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Contact1 {
  /** Type of the contact. This is a code. Please refer to the available [Contact types](#tag/Reference-codes/Contact-types) for the possible values. */
  contactType: string;
  /** Email address of the contact. Mandatory in some cases. Please see [Guidelines](https://developer.postnl.nl/browse-apis/send-and-track/labelling-webservice/). */
  email?: string;
  /** Mobile phone number of the contact. Mandatory in some cases. Please see [Guidelines](https://developer.postnl.nl/browse-apis/send-and-track/labelling-webservice/). */
  sMSNr?: string;
  /** Phone number of the contact */
  telNr?: string;
}

export const contact1Schema: Schema<Contact1> = object({
  contactType: ['ContactType', string()],
  email: ['Email', optional(string())],
  sMSNr: ['SMSNr', optional(string())],
  telNr: ['TelNr', optional(string())],
});
