/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CountrycodeEnum
 */
export enum CountrycodeEnum {
  NL = 'NL',
  BE = 'BE',
}

/**
 * Schema for CountrycodeEnum
 */
export const countrycodeEnumSchema: Schema<CountrycodeEnum> = stringEnum(CountrycodeEnum);
