/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CountryCode1Enum
 */
export enum CountryCode1Enum {
  NL = 'NL',
  BE = 'BE',
}

/**
 * Schema for CountryCode1Enum
 */
export const countryCode1EnumSchema: Schema<CountryCode1Enum> = stringEnum(CountryCode1Enum);
