/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Shipment2, shipment2Schema } from './shipment2';

/** The current status and old statuses of the shipment */
export interface CurrentStatus {
  shipment?: Shipment2[];
}

export const currentStatusSchema: Schema<CurrentStatus> = object({
  shipment: ['Shipment', optional(array(lazy(() => shipment2Schema)))],
});
