/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Customer1 {
  /** The customer code of the shipment */
  customerCode?: string;
  /** The customer number of the shipment */
  customerNumber?: string;
  /** The customer name */
  name?: string;
}

export const customer1Schema: Schema<Customer1> = object({
  customerCode: ['CustomerCode', optional(string())],
  customerNumber: ['CustomerNumber', optional(string())],
  name: ['Name', optional(string())],
});
