/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { DayEnum, dayEnumSchema } from './dayEnum';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface CutOffTime {
  /** The day for which the cutoff time applies. 00 is your default cutoff that applies to all otherwise not specified days, 01 to 07 is Monday to Sunday. */
  day: DayEnum;
  /** Specifies whether you are available to process shipments during the selected day */
  available?: boolean;
  /** Specifies the type belonging to the cutoff time. */
  type?: TypeEnum;
  /** Specifies the cutoff time (mandatory when Available is true) */
  time?: string;
}

export const cutOffTimeSchema: Schema<CutOffTime> = object({
  day: ['Day', dayEnumSchema],
  available: ['Available', optional(boolean())],
  type: ['Type', optional(typeEnumSchema)],
  time: ['Time', optional(string())],
});
