/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** The options belonging to the pickup location. The delivery options RETA, UL, PU, DO, BW, RT and BWUL can be shown in the response. Please ignore these codes. These codes are internal PostNL codes. */
export interface DeliveryOptions {
  string?: string[];
}

export const deliveryOptionsSchema: Schema<DeliveryOptions> = object({
  string: ['string', optional(array(string()))],
});
