/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeliveryOption1Enum
 */
export enum DeliveryOption1Enum {
  PG = 'PG',
  PA = 'PA',
  PGEX = 'PG_EX',
}

/**
 * Schema for DeliveryOption1Enum
 */
export const deliveryOption1EnumSchema: Schema<DeliveryOption1Enum> = stringEnum(DeliveryOption1Enum);
