/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeliveryOptions1Enum
 */
export enum DeliveryOptions1Enum {
  PG = 'PG',
  PA = 'PA',
  PGEX = 'PG_EX',
}

/**
 * Schema for DeliveryOptions1Enum
 */
export const deliveryOptions1EnumSchema: Schema<DeliveryOptions1Enum> = stringEnum(DeliveryOptions1Enum);
