/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Dimension1 {
  /** The weight of the shipment */
  weight?: string;
  /** The height of the shipment */
  height?: string;
  /** The length of the shipment */
  length?: string;
  /** The width of the shipment */
  width?: string;
  /** The volume of the shipment */
  volume?: string;
}

export const dimension1Schema: Schema<Dimension1> = object({
  weight: ['Weight', optional(string())],
  height: ['Height', optional(string())],
  length: ['Length', optional(string())],
  width: ['Width', optional(string())],
  volume: ['Volume', optional(string())],
});
