/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error6 {
  /** The error code */
  code?: string;
  /** The error description */
  description?: string;
}

export const error6Schema: Schema<Error6> = object({
  code: ['code', optional(string())],
  description: ['description', optional(string())],
});
