/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error5 {
  /** The error message */
  errorMsg?: string;
  /** The error code */
  errorNumber?: string;
}

export const error5Schema: Schema<Error5> = object({
  errorMsg: ['ErrorMsg', optional(string())],
  errorNumber: ['ErrorNumber', optional(string())],
});
