/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error7 {
  /** The error reason */
  error?: string;
  /** The error code */
  code?: string;
  /** The description of the error */
  description?: string;
}

export const error7Schema: Schema<Error7> = object({
  error: ['Error', optional(string())],
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
});
