/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error {
  status?: string;
  title?: string;
  detail?: string;
}

export const errorSchema: Schema<Error> = object({
  status: ['status', optional(string())],
  title: ['title', optional(string())],
  detail: ['detail', optional(string())],
});
