/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Event {
  /** The event code */
  code?: string;
  /** The event description */
  description?: string;
  /** Location code of the destination */
  destinationLocationCode?: string;
  /** The current location code */
  locationCode?: string;
  /** The route code */
  routeCode?: string;
  /** The route number */
  routeNumber?: string;
  /** Timestamp of the event */
  timeStamp?: string;
}

export const eventSchema: Schema<Event> = object({
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
  destinationLocationCode: ['DestinationLocationCode', optional(string())],
  locationCode: ['LocationCode', optional(string())],
  routeCode: ['RouteCode', optional(string())],
  routeNumber: ['RouteNumber', optional(string())],
  timeStamp: ['TimeStamp', optional(string())],
});
