/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The expected delivery timeframe */
export interface Expectation {
  /** The start of the timeframe */
  eTAFrom?: string;
  /** The end of the timeframe */
  eTATo?: string;
}

export const expectationSchema: Schema<Expectation> = object({
  eTAFrom: ['ETAFrom', optional(string())],
  eTATo: ['ETATo', optional(string())],
});
