/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ExtraField {
  key?: string;
  value?: string;
}

export const extraFieldSchema: Schema<ExtraField> = object({
  key: ['Key', optional(string())],
  value: ['Value', optional(string())],
});
