/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Detail, detailSchema } from './detail';

export interface Fault {
  faultstring?: string;
  detail?: Detail;
}

export const faultSchema: Schema<Fault> = object({
  faultstring: ['faultstring', optional(string())],
  detail: ['detail', optional(lazy(() => detailSchema))],
});
