/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Location1, location1Schema } from './location1';

export interface GetLocationsResult1 {
  responseLocation?: Location1;
}

export const getLocationsResult1Schema: Schema<GetLocationsResult1> = object({
  responseLocation: ['ResponseLocation', optional(lazy(() => location1Schema))],
});
