/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Location1, location1Schema } from './location1';

export interface GetLocationsResult {
  responseLocation?: Location1[];
}

export const getLocationsResultSchema: Schema<GetLocationsResult> = object({
  responseLocation: [
    'ResponseLocation',
    optional(array(lazy(() => location1Schema))),
  ],
});
