/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { MergedLabel, mergedLabelSchema } from './mergedLabel';
import { ResponseShipment1, responseShipment1Schema } from './responseShipment1';

export interface LabellingResponse {
  /** The merged label output; only returned if the printer type selected in your request merges the pdf labels into a single file (e.g. using GraphicFile|Merge). */
  mergedLabels?: MergedLabel[];
  responseShipments?: ResponseShipment1[];
}

export const labellingResponseSchema: Schema<LabellingResponse> = object({
  mergedLabels: [
    'MergedLabels',
    optional(array(lazy(() => mergedLabelSchema))),
  ],
  responseShipments: [
    'ResponseShipments',
    optional(array(lazy(() => responseShipment1Schema))),
  ],
});
