/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Label1 {
  /** Base64 encoded label content */
  content?: string;
  /** Type of the label. See Guidelines */
  labeltype?: string;
  /** Content type of the label, e.g. zebra of pdf. Note: It is not recommended to send .PDF files/labels directly to a Zebra printer. See Guidelines. */
  outputType?: string;
}

export const label1Schema: Schema<Label1> = object({
  content: ['Content', optional(string())],
  labeltype: ['Labeltype', optional(string())],
  outputType: ['OutputType', optional(string())],
});
