/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LanguageEnum
 */
export enum LanguageEnum {
  NL = 'NL',
  EN = 'EN',
  CN = 'CN',
  DE = 'DE',
  FR = 'FR',
}

/**
 * Schema for LanguageEnum
 */
export const languageEnumSchema: Schema<LanguageEnum> = stringEnum(LanguageEnum);
