/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  GetLocationsResult1,
  getLocationsResult1Schema,
} from './getLocationsResult1';

export interface LocationResponse {
  getLocationsResult?: GetLocationsResult1;
}

export const locationResponseSchema: Schema<LocationResponse> = object({
  getLocationsResult: [
    'GetLocationsResult',
    optional(lazy(() => getLocationsResult1Schema)),
  ],
});
