/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  GetLocationsResult,
  getLocationsResultSchema,
} from './getLocationsResult';

export interface LocationsResponse {
  getLocationsResult?: GetLocationsResult;
}

export const locationsResponseSchema: Schema<LocationsResponse> = object({
  getLocationsResult: [
    'GetLocationsResult',
    optional(lazy(() => getLocationsResultSchema)),
  ],
});
