/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Label, labelSchema } from './label';

export interface MergedLabel {
  barcodes?: string[];
  labels?: Label[];
}

export const mergedLabelSchema: Schema<MergedLabel> = object({
  barcodes: ['Barcodes', optional(array(string()))],
  labels: ['Labels', optional(array(lazy(() => labelSchema)))],
});
