/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Message1 {
  /** ID of the message */
  messageID: string;
  /** Date/time of sending the message. Format: dd-mm-yyyy hh:mm:ss */
  messageTimeStamp: string;
  /** Printer type that will be used to process the label, e.g. Zebra printer or PDF See [Printer types](#tag/Reference-codes/Printer-types) for the available printer types. */
  printertype: string;
}

export const message1Schema: Schema<Message1> = object({
  messageID: ['MessageID', string()],
  messageTimeStamp: ['MessageTimeStamp', string()],
  printertype: ['Printertype', string()],
});
