/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Message {
  /** ID of the message */
  messageID: string;
  /** Date/time of sending the message. Format: dd-mm-yyyy hh:mm:ss */
  messageTimeStamp: string;
}

export const messageSchema: Schema<Message> = object({
  messageID: ['MessageID', string()],
  messageTimeStamp: ['MessageTimeStamp', string()],
});
