/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface OldStatus {
  /** The status timestamp */
  timeStamp?: string;
  /** The status code */
  statusCode?: string;
  /** The status description */
  statusDescription?: string;
  /** The phase code */
  phaseCode?: string;
  /** The phase description */
  phaseDescription?: string;
}

export const oldStatusSchema: Schema<OldStatus> = object({
  timeStamp: ['TimeStamp', optional(string())],
  statusCode: ['StatusCode', optional(string())],
  statusDescription: ['StatusDescription', optional(string())],
  phaseCode: ['PhaseCode', optional(string())],
  phaseDescription: ['PhaseDescription', optional(string())],
});
