/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Friday1, friday1Schema } from './friday1';
import { Monday1, monday1Schema } from './monday1';
import { Saturday1, saturday1Schema } from './saturday1';
import { Sunday1, sunday1Schema } from './sunday1';
import { Thursday1, thursday1Schema } from './thursday1';
import { Tuesday1, tuesday1Schema } from './tuesday1';
import { Wednesday1, wednesday1Schema } from './wednesday1';

/** The standard opening times of the pickup location */
export interface OpeningHours1 {
  monday?: Monday1;
  tuesday?: Tuesday1;
  wednesday?: Wednesday1;
  thursday?: Thursday1;
  friday?: Friday1;
  saturday?: Saturday1;
  sunday?: Sunday1;
}

export const openingHours1Schema: Schema<OpeningHours1> = object({
  monday: ['Monday', optional(lazy(() => monday1Schema))],
  tuesday: ['Tuesday', optional(lazy(() => tuesday1Schema))],
  wednesday: ['Wednesday', optional(lazy(() => wednesday1Schema))],
  thursday: ['Thursday', optional(lazy(() => thursday1Schema))],
  friday: ['Friday', optional(lazy(() => friday1Schema))],
  saturday: ['Saturday', optional(lazy(() => saturday1Schema))],
  sunday: ['Sunday', optional(lazy(() => sunday1Schema))],
});
