/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { StringEnum, stringEnumSchema } from './stringEnum';

/** The delivery options for which a delivery date is returned. Only one delivery option is specified. See [Delivery Options](#tag/Reference-codes/Delivery-options) for possible values. */
export interface Options {
  string?: StringEnum;
}

export const optionsSchema: Schema<Options> = object({
  string: ['string', optional(stringEnumSchema)],
});
