/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { String1Enum, string1EnumSchema } from './string1Enum';

/** The delivery option for which the timeframe is calculated. See [Delivery Options](#tag/Reference-codes/Delivery-options) for possible values. */
export interface Options2 {
  string?: String1Enum;
}

export const options2Schema: Schema<Options2> = object({
  string: ['string', optional(string1EnumSchema)],
});
