/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Option1Enum
 */
export enum Option1Enum {
  Daytime = 'Daytime',
  Evening = 'Evening',
  Sunday = 'Sunday',
  Sameday = 'Sameday',
  Today = 'Today',
  Enum08001000 = '08:00-10:00',
  Enum08001200 = '08:00-12:00',
  Enum08001700 = '08:00-17:00',
}

/**
 * Schema for Option1Enum
 */
export const option1EnumSchema: Schema<Option1Enum> = stringEnum(Option1Enum);
