/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Options1Enum
 */
export enum Options1Enum {
  Daytime = 'Daytime',
  Today = 'Today',
  Sameday = 'Sameday',
  Evening = 'Evening',
  Morning = 'Morning',
  Noon = 'Noon',
  Sunday = 'Sunday',
  Afternoon = 'Afternoon',
}

/**
 * Schema for Options1Enum
 */
export const options1EnumSchema: Schema<Options1Enum> = stringEnum(Options1Enum);
