/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Option2Enum
 */
export enum Option2Enum {
  Daytime = 'Daytime',
  Evening = 'Evening',
  Sameday = 'Sameday',
  Sunday = 'Sunday',
  Today = 'Today',
  Enum08001000 = '08:00-10:00',
  Enum08001200 = '08:00-12:00',
  Enum08001700 = '08:00-17:00',
  Enum08000900 = '08:00-09:00',
  Pickup = 'Pickup',
}

/**
 * Schema for Option2Enum
 */
export const option2EnumSchema: Schema<Option2Enum> = stringEnum(Option2Enum);
