/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OriginCountryCodeEnum
 */
export enum OriginCountryCodeEnum {
  NL = 'NL',
  BE = 'BE',
}

/**
 * Schema for OriginCountryCodeEnum
 */
export const originCountryCodeEnumSchema: Schema<OriginCountryCodeEnum> = stringEnum(OriginCountryCodeEnum);
