/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ProductOption1, productOption1Schema } from './productOption1';

/** A list of product options. */
export interface ProductOptions {
  productOption?: ProductOption1;
}

export const productOptionsSchema: Schema<ProductOptions> = object({
  productOption: ['ProductOption', optional(lazy(() => productOption1Schema))],
});
