/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ProductOption1 {
  /** The product option code for this ProductOption. */
  optionCode?: string;
  /** The characteristic of the ProductOption. */
  characteristicCode?: string;
}

export const productOption1Schema: Schema<ProductOption1> = object({
  optionCode: ['OptionCode', optional(string())],
  characteristicCode: ['CharacteristicCode', optional(string())],
});
