/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ReasonNoTimeframe, reasonNoTimeframeSchema } from './reasonNoTimeframe';

export interface ReasonNoTimeframes {
  /** The reason why no timeframe was returned */
  reasonNoTimeframe?: ReasonNoTimeframe[];
}

export const reasonNoTimeframesSchema: Schema<ReasonNoTimeframes> = object({
  reasonNoTimeframe: [
    'ReasonNoTimeframe',
    optional(array(lazy(() => reasonNoTimeframeSchema))),
  ],
});
