/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Error6, error6Schema } from './error6';
import { Warning1, warning1Schema } from './warning1';

export interface ResponseShipment {
  /** Possible errors. See the [Error Codes](#tag/Error codes) for possible values */
  errors?: Error6[];
  /** Possible warnings. See the [Error Codes](#tag/Error codes) for possible values */
  warnings?: Warning1[];
  /** The barcode used */
  barcode?: string;
}

export const responseShipmentSchema: Schema<ResponseShipment> = object({
  errors: ['Errors', optional(array(lazy(() => error6Schema)))],
  warnings: ['Warnings', optional(array(lazy(() => warning1Schema)))],
  barcode: ['Barcode', optional(string())],
});
