/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShipmentTypeEnum
 */
export enum ShipmentTypeEnum {
  Gift = 'Gift',
  Documents = 'Documents',
  EnumCommercialGoods = 'Commercial Goods',
  EnumCommercialSample = 'Commercial Sample',
  EnumReturnedGoods = 'Returned Goods',
}

/**
 * Schema for ShipmentTypeEnum
 */
export const shipmentTypeEnumSchema: Schema<ShipmentTypeEnum> = stringEnum(ShipmentTypeEnum);
