/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Signature {
  /** The barcode of the shipment for which the signature is returned */
  barcode?: string;
  /** The date of the signature */
  signatureDate?: string;
  /** The signature content; base64 encoded GIF format. */
  signatureImage?: string;
}

export const signatureSchema: Schema<Signature> = object({
  barcode: ['Barcode', optional(string())],
  signatureDate: ['SignatureDate', optional(string())],
  signatureImage: ['SignatureImage', optional(string())],
});
