/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The current status of the shipment (see the [Status codes](#tag/TandT-status-codes/Status-codes) for possible values. */
export interface Status {
  /** The status timestamp */
  timeStamp?: string;
  /** The status code */
  statusCode?: string;
  /** The status description */
  statusDescription?: string;
  /** The phase code */
  phaseCode?: string;
  /** The phase description */
  phaseDescription?: string;
}

export const statusSchema: Schema<Status> = object({
  timeStamp: ['TimeStamp', optional(string())],
  statusCode: ['StatusCode', optional(string())],
  statusDescription: ['StatusDescription', optional(string())],
  phaseCode: ['PhaseCode', optional(string())],
  phaseDescription: ['PhaseDescription', optional(string())],
});
