/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StringEnum
 */
export enum StringEnum {
  Daytime = 'Daytime',
  Evening = 'Evening',
  Morning = 'Morning',
  Noon = 'Noon',
  Sunday = 'Sunday',
  Today = 'Today',
  Afternoon = 'Afternoon',
}

/**
 * Schema for StringEnum
 */
export const stringEnumSchema: Schema<StringEnum> = stringEnum(StringEnum);
