/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Sunday1 {
  string?: string;
}

export const sunday1Schema: Schema<Sunday1> = object({
  string: ['string', optional(string())],
});
