/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Sustainability score; see [Sustainability codes](#tag/Reference-codes/Sustainability-codes) for possible values. */
export interface Sustainability2 {
  /** Sustainability score code */
  code?: string;
  /** Sustainability score code description */
  description?: string;
}

export const sustainability2Schema: Schema<Sustainability2> = object({
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
});
