/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { CodeEnum, codeEnumSchema } from './codeEnum';

/** Sustainability score; see [Sustainability codes](#tag/Reference-codes/Sustainability-codes) for possible values. */
export interface Sustainability {
  /** Sustainability score code */
  code?: CodeEnum;
  /** Sustainability score code description */
  description?: string;
}

export const sustainabilitySchema: Schema<Sustainability> = object({
  code: ['Code', optional(codeEnumSchema)],
  description: ['Description', optional(string())],
});
