/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Sustainability score */
export interface Sustainability4 {
  /** Sustainability score code */
  code?: string;
  /** Sustainability score code description */
  description?: string;
}

export const sustainability4Schema: Schema<Sustainability4> = object({
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
});
