/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  TimeframeTimeframe,
  timeframeTimeframeSchema,
} from './timeframeTimeframe';

export interface Timeframes1 {
  timeframeTimeframe?: TimeframeTimeframe[];
}

export const timeframes1Schema: Schema<Timeframes1> = object({
  timeframeTimeframe: [
    'TimeframeTimeframe',
    optional(array(lazy(() => timeframeTimeframeSchema))),
  ],
});
