/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Timeframes1, timeframes1Schema } from './timeframes1';

export interface Timeframe1 {
  /** The expected date of delivery */
  date?: string;
  timeframes?: Timeframes1;
}

export const timeframe1Schema: Schema<Timeframe1> = object({
  date: ['Date', optional(string())],
  timeframes: ['Timeframes', optional(lazy(() => timeframes1Schema))],
});
