/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ReasonNoTimeframes,
  reasonNoTimeframesSchema,
} from './reasonNoTimeframes';
import { Timeframes, timeframesSchema } from './timeframes';

export interface TimeframeResponse {
  timeframes?: Timeframes;
  reasonNoTimeframes?: ReasonNoTimeframes;
}

export const timeframeResponseSchema: Schema<TimeframeResponse> = object({
  timeframes: ['Timeframes', optional(lazy(() => timeframesSchema))],
  reasonNoTimeframes: [
    'ReasonNoTimeframes',
    optional(lazy(() => reasonNoTimeframesSchema)),
  ],
});
