/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Warning3, warning3Schema } from './warning3';

export interface Warnings {
  warning?: Warning3;
}

export const warningsSchema: Schema<Warnings> = object({
  warning: ['Warning', optional(lazy(() => warning3Schema))],
});
