/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Warning3 {
  /** Warning message */
  message?: string;
  /** Warning code */
  code?: string;
}

export const warning3Schema: Schema<Warning3> = object({
  message: ['Message', optional(string())],
  code: ['Code', optional(string())],
});
