/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Warnings1 {
  /** The Warning code */
  code?: string;
  /** The warning description */
  description?: string;
}

export const warnings1Schema: Schema<Warnings1> = object({
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
});
