/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { Option2Enum, option2EnumSchema } from './option2Enum';

export interface Warning {
  /** Deliverydate that triggered the warning */
  deliveryDate?: string;
  /** Warning code (for a possible list of warnings, see the generic error codes page) */
  code?: string;
  /** Warning description (for a possible list of warnings, see the generic error codes page) */
  description?: string;
  /** The option that triggered the warning */
  options?: Option2Enum[];
}

export const warningSchema: Schema<Warning> = object({
  deliveryDate: ['DeliveryDate', optional(string())],
  code: ['Code', optional(string())],
  description: ['Description', optional(string())],
  options: ['Options', optional(array(option2EnumSchema))],
});
