/**
 * PostNL Ecommerce APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Warning2 {
  /** The warning message */
  message?: string;
  /** The warning code */
  code?: string;
}

export const warning2Schema: Schema<Warning2> = object({
  message: ['Message', optional(string())],
  code: ['Code', optional(string())],
});
